[MeterBarRaw0]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw0
X=10
Y=300
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw1]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw1
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw2]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw2
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw3]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw3
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw4]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw4
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw5]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw5
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw6]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw6
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw7]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw7
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw8]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw8
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw9]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw9
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw10]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw10
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBarRaw11]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioRaw11
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#