[MeterBar0]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed0
X=10
Y=0
W=#BarWidth#
H=#BarHeight#

[MeterBar1]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed1
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar2]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed2
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar3]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed3
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar4]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed4
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar5]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed5
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar6]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed6
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar7]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed7
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar8]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed8
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar9]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed9
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar10]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed10
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#

[MeterBar11]
Meter=BAR
BarColor=#Color#
MeasureName=MeasureAudioSmoothed11
X=#BarGap#R
Y=r
W=#BarWidth#
H=#BarHeight#